### ISSUE TITLE
How to set up https for phant on my localhost?

### ISSUE THREAD

**Issue by lautiamkok** [sparkfun/phant#197]
I have phant installed on my local machine and got it running at http://localhost:8080

How can I run it at https? 

I have created the cert and key and I changed the code in https_server.js manually:

/usr/local/lib/node_modules/phant/lib/https_server.js

```
app.credentials = function() {

  return {
    cert: fs.readFileSync('/opt/certs/example.com.crt'),
    key: fs.readFileSync('/opt/certs/example.com.key')
  };

};
```

Then I tested at https://localhost:8080

I get this error:

**This webpage is not available

ERR_CONNECTION_CLOSED**

How can I set up https for phant correctly then?

**Comment by m4ddav3** [comment]
@lautiamkok You'll need to edit `/usr/local/bin/phant` and change all instances of `HttpServer` to `HttpsServer`

**Comment by lautiamkok** [comment]
@m4ddav3 thanks for the tip!

**Comment by chenmingzhang** [comment]
i received 
$phant
process.env.PHANT_SERVER_STLE = undefined
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.app.credentials (/usr/lib64/node_modules/phant/lib/https_server.js:80:14)
    at Object.app.listen (/usr/lib64/node_modules/phant/lib/https_server.js:42:41)
    at Object.<anonymous> (/usr/lib64/node_modules/phant/.bin/serve:57:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)


when i change HttpServer to HttpsServer.

any updates? thanks
