### ISSUE TITLE
Error when sent input

### ISSUE THREAD

**Issue by gaew** [sparkfun/phant#233]
(node:3344) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/opt/bitnami/nodejs/lib/node_modules/phant/lib/validator.js:173
      if (!data.hasOwnProperty(key)) {
                ^

TypeError: data.hasOwnProperty is not a function
    at /opt/bitnami/nodejs/lib/node_modules/phant/lib/validator.js:173:17
    at /opt/bitnami/nodejs/lib/node_modules/phant/node_modules/phant-meta-nedb/lib/phant-meta-nedb.js:188:5
    at callback (/opt/bitnami/nodejs/lib/node_modules/phant/node_modules/nedb/lib/executor.js:30:17)
    at Cursor.execFn (/opt/bitnami/nodejs/lib/node_modules/phant/node_modules/nedb/lib/datastore.js:449:14)
    at Cursor._exec (/opt/bitnami/nodejs/lib/node_modules/phant/node_modules/nedb/lib/cursor.js:172:17)
    at /opt/bitnami/nodejs/lib/node_modules/phant/node_modules/nedb/lib/executor.js:40:13
    at Immediate.process (/opt/bitnami/nodejs/lib/node_modules/phant/node_modules/nedb/node_modules/async/lib/async.js:731:21)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
